app = 'fso-part-11'
primary_region = 'lax'

[build]

[env]
  PORT = "5001"

[processes]
  app = "node app.js"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
